### ISSUE TITLE
create:andesite_bricks doesn't exist

### ISSUE THREAD

**Issue by Gwen-Del** [xyroc/DungeonCrawl#150]
I think the block create:andesite_bricks doesn't exist because it crash my server -> [Create issue](https://github.com/Creators-of-Create/Create/issues/5697)

**Comment by xyroc** [comment]
I don't think Dungeon Crawl is responsible for this crash. All i can see in the logs is that the crash occurred during generation of a plains village because one of the jigsaw pieces uses the `create:andesite_bricks` block, which does not exist. Dungeon Crawl does not use jigsaw pieces and is not mentioned anywhere in the crash log.
If you can reproduce the issue, try installing the [Cyanide ](https://www.curseforge.com/minecraft/mc-mods/cyanide) mod and then have it crash again. The additional information it provides might help pinpoint the issue.

**Comment by Gwen-Del** [comment]
I will try the Cyanide mod but I searched on the create mod git and on all addons that I use and I have never found an occurrence of the block "create:andesite_bricks". But I did find some in the Dungeon Crawl mod (for exemple "src/main/resources/data/dungeoncrawl/theming/primary_themes/create/andesite.json").

**Comment by Gwen-Del** [comment]
> I don't think Dungeon Crawl is responsible for this crash. All i can see in the logs is that the crash occurred during generation of a plains village because one of the jigsaw pieces uses the `create:andesite_bricks` block, which does not exist. Dungeon Crawl does not use jigsaw pieces and is not mentioned anywhere in the crash log. If you can reproduce the issue, try installing the [Cyanide ](https://www.curseforge.com/minecraft/mc-mods/cyanide) mod and then have it crash again. The additional information it provides might help pinpoint the issue.

I will try the Cyanide mod but I searched on the create mod git and on all addons that I use and I have never found an occurrence of the block "create:andesite_bricks". But I did find some in the Dungeon Crawl mod (for exemple "src/main/resources/data/dungeoncrawl/theming/primary_themes/create/andesite.json").

**Comment by Gwen-Del** [comment]
I will try the Cyanide mod but I searched on the create mod git and on all addons that I use and I have never found an occurrence of the block "create:andesite_bricks". But I did find some in the Dungeon Crawl mod (for exemple "src/main/resources/data/dungeoncrawl/theming/primary_themes/create/andesite.json").

**Comment by xyroc** [comment]
Yes, i am aware of that, but that is not what is causing the crash. I am not surprised you can't find the actual cause because structure files are nbt files. Text search doesn't work on those.
