### ISSUE TITLE
Loot Tables and Spawners

### ISSUE THREAD

**Issue by KintsugiSoul** [xyroc/DungeonCrawl#60]
Make a way to change loot tables for each layer as well as a way to change the chance of getting it on that layer, and then using your tags config let them add enchantments per layer as well.

Additionally but no as important, allow customizable spawners, both with the option to change what spawns and what gear mobs spawn with if they are able  as well as a chance that spawner will appear on that layer

I feel like these changes, especially the first, would help modpack creators a lot when making modpacks.

**Comment by xyroc** [comment]
Most of the things you mentioned are already possible. You can
- change every loot table the mod uses
- change spawners on a per layer basis (entities, equipment and even potion effects)
The spawner changes aren't documented at the moment, but they are very straightforward.

> chance of getting it on that layer

Not sure what that means. Every chest placed receives the loot table for the layer it is in, unless the room it is in uses a different one.

Also, I don't recommend using the special item tags config right now since I am going to replace it with a datapack-driven version and probably change some things.
