### ISSUE TITLE
DungeonCrawl 1.16.5-2.3.0 no longer generates Lootr chests

### ISSUE THREAD

**Issue by Thombias** [xyroc/DungeonCrawl#81]
So i updated DungeonCrawl in my modpack from version 2.2.4 to 2.3.0 and immediately noticed i had vanilla chests generating in the dungeons instead of the chests from the Lootr mod (Which was previously supported).

I assume this has something to do with the fact that parts of the mod have been reworked? Or it may be because of the addition of dungeon types or something.

If required, i can provide a mod list via a screenshot.
I'm also using Forge 36.2.0 now, previously used Forge 36.1.0. Could that be the issue?

**Comment by noobanidus** [comment]
I can see exactly where the issue is. Hopefully I'll have a PR to fix it by the end of today.

EDIT: Report on my repository: https://github.com/noobanidus/Lootr/issues/44

EDIT 2: Clarification, the new Loot class in the treasure package uses the *instance* of the LockableLootTileEntity to set the loot table. It needs to be tweaked to use the *static* method of the LockableLootTileEntity instead, which requires changing the method signature and passing the (generation context) world in. 

EDIT 3: Further clarification: I hook into the static method with a mixin. I can't hook in to the instance method as the `world` hasn't been set for the tile (and when it is set, it's the *server* world rather than the generation context; using delays results in server lock-ups). Hence, static method is superior.
